FROM jenkins/jenkins:lts
USER root
COPY --from=docker:latest /usr/local/bin/docker /usr/local/bin/docker
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*
USER jenkins
